import Foundation

/// A precompiled segment in an HTTP route pattern.
///
/// This is primarily emitted by ``Route``. It is public so macro expansions in
/// client modules can construct endpoint metadata.
public enum RouteSegment: Sendable, Equatable {
    case literal(String)
    case parameter(String)
    case wildcard(String)
}

/// The method and path segments served by an endpoint.
///
/// A route declaration emitted by ``Route`` contains one definition per HTTP
/// method.
public struct RouteDefinition: Sendable {
    public let method: Method
    public let segments: [RouteSegment]

    public init(method: Method, segments: [RouteSegment]) {
        self.method = method
        self.segments = segments
    }
}

/// A value that can be decoded from a percent-decoded path parameter.
///
/// Conform domain identifiers to this protocol to use them with ``PathParam``.
public protocol PathValue: Sendable {
    init?(pathValue: String)
}

/// Decodes a value for code generated by ``Route``.
public func decodePathValue<Value: PathValue>(_ type: Value.Type, from pathValue: String) -> Value? {
    Value(pathValue: pathValue)
}

/// A value that can be decoded from a percent-decoded query parameter.
///
/// Conform domain types to this protocol to use them with ``QueryParam(_:)``.
public protocol QueryValue: Sendable {
    init?(queryValue: String)
}

/// Decodes a value for code generated by ``Route``.
public func decodeQueryValue<Value: QueryValue>(_ type: Value.Type, from queryValue: String) -> Value? {
    Value(queryValue: queryValue)
}

extension String: PathValue {
    public init?(pathValue: String) { self = pathValue }
}

extension Bool: PathValue {
    public init?(pathValue: String) {
        switch pathValue.lowercased() {
        case "true": self = true
        case "false": self = false
        default: return nil
        }
    }
}

extension Int: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension Int8: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension Int16: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension Int32: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension Int64: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension UInt: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension UInt8: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension UInt16: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension UInt32: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension UInt64: PathValue { public init?(pathValue: String) { self.init(pathValue) } }
extension UUID: PathValue { public init?(pathValue: String) { self.init(uuidString: pathValue) } }

extension String: QueryValue { public init?(queryValue: String) { self = queryValue } }

extension Bool: QueryValue {
    public init?(queryValue: String) {
        switch queryValue.lowercased() {
        case "true": self = true
        case "false": self = false
        default: return nil
        }
    }
}

extension Int: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension Int8: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension Int16: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension Int32: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension Int64: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension UInt: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension UInt8: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension UInt16: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension UInt32: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension UInt64: QueryValue { public init?(queryValue: String) { self.init(queryValue) } }
extension UUID: QueryValue { public init?(queryValue: String) { self.init(uuidString: queryValue) } }

/// A type whose route metadata and request dispatcher are generated by ``Route``.
public protocol RouteEndpoint: Sendable {
    static var routeDefinitions: [RouteDefinition] { get }
    static func respond(to request: Request) async throws -> Response
}
